config/routes.rb
HolidayMailer::Application.routes.draw do
  resources :people
  resources :households
  resources :notes
  resources :batches do
    member do
      put 'activate'
    end
  end
  
  get 'login' => 'sessions#new', :as => :login
  put 'sessions/facebook_oauth_token_update' => 'sessions#facebook_oauth_token_update', :as => :facebook_oauth_token_update
  delete 'sessions/logout' => 'sessions#destroy', :as => :logout

  # Home Page
  root :to => 'people#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :household

  before_create :ensure_household
  after_destroy :remove_empty_household
  
  
  def full_name
    if first_name.present? && last_name.present?
      return "#{first_name} #{last_name}"
    else
      return first_name || last_name
    end
  end
  
  def full_email_address
    if full_name.present? && email.present?
      "#{full_name} <#{email}>"
    elsif email.present?
      email
    else
      nil
    end
  end
    
protected
  def ensure_household
    unless self.household_id
      self.household = Household.create!
    end
  end
  
  def remove_empty_household
    if self.household.people.count(true) == 0
      self.household.destroy
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @households = Household.includes(:people).all.sort_by &:last_name_of_first_person
  end

  def new
    @person = Person.new(params[:person])
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(params[:person])

    if @person.save
      flash[:notice] = "#{@person.full_name} was successfully added."
      redirect_to_people_list_showing(@person.household)
    else
      render :action => "new"
    end
  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(params[:person])
      flash[:notice] = 'Person was successfully changed.'
      redirect_to_people_list_showing(@person.household)
    else
      render :action => "edit"
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    flash[:notice] = "#{@person.full_name} deleted."
    redirect_to_people_list_showing(@person.household)
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def class_for_household_div(household)
    classes = []
    classes << dom_id(household)
    classes << "letter_#{household.first_letter_of_last_name_of_first_person.downcase}"
    classes << "note_sent" if household.note_sent?
    classes.join(' ')
  end
  
  def link_to_new_note(household)
    if household.active_notes_count == 0
      link_to "Send mail", new_note_path(:note => {:household_id => household.id, :batch_id => Batch.active_batch.id})
    elsif household.active_notes_count == 1
      link_to "Email sent by #{household.notes.active.last.sender.first_name}", new_note_path(:note => {:household_id => household.id, :batch_id => Batch.active_batch.id})
    else
      link_to "#{household.active_notes_count} emails sent (last by #{household.notes.active.last.sender.first_name})", new_note_path(:note => {:household_id => household.id, :batch_id => Batch.active_batch.id})
    end
  end
end

app/views/people/_index_javascript.html.erb
<% if flash[:scroll_to] %>
  <% content_for :javascript do %>
  <script type="text/javascript" charset="utf-8">
    $(function(){
      var el = $('<%= flash[:scroll_to] %>');
      if (el.length > 0) {
        el[0].scrollIntoView();
      }
    });
  </script>
  <% end %>
<% end %>

app/views/people/edit.html.haml
%h1 Editing person

= semantic_form_for(@person, :html => {:class => 'person_form'}) do |f|
  = errors_for(@person)

  = f.inputs do
    = f.input :first_name
    = f.input :last_name
    = f.input :email

  = f.actions do
    = f.action(:submit)

= link_to 'Cancel and go back', people_path

app/views/people/index.html.haml
= render :partial => 'index_javascript'

%h1 The List

-for household in @households
  - if household.people.count > 1
    .household{ :class => class_for_household_div(household) }
      = household.description
      = link_to 'Edit', edit_household_path(household)
      = link_to_new_note(household)
      = link_to 'Add to household', new_person_path(:person => {:household_id => household.id})
    
      -for person in household.people
        .person
          .email= person.email
          = person.full_name
          = link_to 'Edit', edit_person_path(person)
          = link_to 'Delete', person, :confirm => 'Are you sure?', :method => :delete
  - else
    - person = household.people.first
    .person{ :class => class_for_household_div(household) }
      .email= person.email
      = person.full_name
      = link_to 'Edit', edit_person_path(person)
      = link_to_new_note(household)
      = link_to 'Delete', person, :confirm => 'Are you sure?', :method => :delete
      = link_to 'Add to household', new_person_path(:person => {:household_id => household.id})

= link_to 'Add person to new household', new_person_path, :class => 'add_person_and_household'

.tip Type a letter on this page to quickly scroll through the list by last name.

app/views/people/new.html.haml
%h1 Add person

= semantic_form_for(@person, :html => {:class => 'person_form'}) do |f|
  = errors_for(@person)

  = f.inputs do
    = f.input :first_name
    = f.input :last_name
    = f.input :email

    =f.hidden_field :household_id

  = f.actions do
    = f.action(:submit)

.back= link_to 'Cancel and go back', people_path