config/routes.rb
HolidayMailer::Application.routes.draw do
  resources :people
  resources :households
  resources :notes
  resources :batches do
    member do
      put 'activate'
    end
  end
  
  get 'login' => 'sessions#new', :as => :login
  put 'sessions/facebook_oauth_token_update' => 'sessions#facebook_oauth_token_update', :as => :facebook_oauth_token_update
  delete 'sessions/logout' => 'sessions#destroy', :as => :logout

  # Home Page
  root :to => 'people#index'
end

app/models/batch.rb
class Batch < ActiveRecord::Base
  has_many :notes

  attr_accessible :name, :subject, :from, :message, :image_filename

  def self.active_batch
    Batch.where(active: true).first
  end

  def activate!
    transaction do
      Batch.update_all(:active => true, :active => false)
      update_attribute(:active, true)
      Household.all.each do |h|
        h.update_active_notes_count
      end
    end
  end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  def index
    @batches = Batch.order('created_at DESC')
  end

  def new
    @batch = Batch.new
    @batch.subject = APP_CONFIG[:default_subject]
    @batch.from = APP_CONFIG[:default_from]
    @batch.message = IO.read(Rails.root.join("config", "default_body.erb"))
    @batch.image_filename = APP_CONFIG[:default_image_filename]
  end

  def create
    Batch.create!(params[:batch])
    redirect_to :action => :index
  end

  def edit
    @batch = Batch.find(params[:id])
  end

  def update
    @batch = Batch.find(params[:id])
    if @batch.update_attributes(params[:batch])
      flash[:notice] = 'Batch updated.'
      redirect_to :action => :index
    else
      render :action => 'edit'
    end
  end

  def activate
    batch = Batch.find(params[:id])
    if batch.activate!
      flash[:notice] = 'Batch activated.'
    else
      flash[:error] = 'There was a problem activating this batch.'
    end
    redirect_to :action => :index
  end
end

app/views/batches/edit.html.haml
%h1 Editing batch

= semantic_form_for(@batch, :html => {:class => 'batch_form'}) do |f|
  = errors_for(@batch)

  = f.inputs do
    = f.input :name
    = f.input :from
    = f.input :subject
    = f.input :image_filename
    = f.input :message, :label => 'Message template'

  = f.actions do
    = f.action(:submit)

= link_to 'Cancel and go back', batches_path

app/views/batches/index.html.haml
= link_to '&lt; Home'.html_safe, root_path

%h1 Batches

= link_to 'New Batch', new_batch_path

-@batches.each do |batch|
  .batch
    .name
      = "Name: <strong>".html_safe + batch.name + "</strong>".html_safe
      = link_to 'Edit', edit_batch_path(batch)
    .active
      = "Active: #{batch.active}"
      = link_to 'Activate', activate_batch_path(batch), :method => :put unless batch.active
    .created_at= "Created at: #{batch.created_at}"
    .count= "Notes sent: #{batch.notes.count}"

app/views/batches/new.html.haml
%h1 Add batch

= semantic_form_for(@batch, :html => {:class => 'batch_form'}) do |f|
  = errors_for(@batch)

  = f.inputs do
    = f.input :name
    = f.input :from
    = f.input :subject
    = f.input :image_filename
    = f.input :message, :label => 'Message template'

  = f.actions do
    = f.action(:submit)

.back= link_to 'Cancel and go back', batches_path